### PR TITLE
Update Trouble shortcuts in init.lua

### PR DESCRIPTION
**Pull request by rabbbit**
I've copied SO MUCH from this file that I feel like I should maybe contribute.

Shortcuts copied from https://github.com/folke/trouble.nvim

Although since you're using lazy.nvim, you might prefer the https://github.com/folke/trouble.nvim?tab=readme-ov-file#-installation instructions.

### CODE REVIEW

**Review by abhinav — COMMENTED** [review]
👀  what version of Trouble do I need for this. `Trouble diagnostics` isn't an option on mine; it needs to be `workspace_diagnostics`, or `document_diagnostics`.

(Also, appreciate the contribution. I knew this was an option in Trouble, but I liked having diagnostics separate from qf and loclist, since I fill those with search results or manual diagnostics sometimes.)

**Comment by rabbbit** [comment]
```
" Generated by vim-plug
" Tue Aug  6 21:04:41 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Zenburn'].commit = '8df765342b2a33c728ce147d6c8e66359378f9d5'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-nvim-lsp-signature-help'].commit = '031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7'
silent! let g:plugs['cmp-omni'].commit = '4ef610bbd85a5ee4e97e09450c0daecbdc60de86'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['ctrlp.vim'].commit = '7c972cb19c8544c681ca345c64ec39e04f4651cc'
silent! let g:plugs['friendly-snippets'].commit = '00ebcaa159e817150bd83bfe2d51fa3b3377d5c4'
silent! let g:plugs['lsp-colors.nvim'].commit = '2bbe7541747fd339bdd8923fc45631a09bb4f1e5'
silent! let g:plugs['lualine.nvim'].commit = '544dd1583f9bb27b393f598475c89809c4d5e86b'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['netrw'].commit = 'f665b0dde1e5a92d3aa1437bb3b2b61e9abe5b90'
silent! let g:plugs['nvim-cmp'].commit = 'ae644feb7b67bf1ce4260c231d1d4300b19c6f30'
silent! let g:plugs['nvim-lspconfig'].commit = '81a19de18990208b678be084597613e2dbe66912'
silent! let g:plugs['nvim-web-devicons'].commit = '3722e3d1fb5fe1896a104eb489e8f8651260b520'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['syntastic'].commit = '8d5e37c29cf5952fbf300b9230bffe424c61a488'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['telescope.nvim'].commit = '3b1600d0fd5172ad9fae00987362ca0ef3d8895d'
silent! let g:plugs['thrift.vim'].commit = 'f627aace1e583aed42f12d2a48b40fc18449a145'
silent! let g:plugs['trouble.nvim'].commit = '6efc446226679fda0547c0fd6a7892fd5f5b15d8'
silent! let g:plugs['vim-fugitive'].commit = '0444df68cd1cdabc7453d6bd84099458327e5513'
silent! let g:plugs['vim-pathogen'].commit = 'ac4dd9494fa9008754e49dff85bff1b5746c89b4'
silent! let g:plugs['vim-python-pep8-indent'].commit = '60ba5e11a61618c0344e2db190210145083c91f8'
silent! let g:plugs['vim-unimpaired'].commit = '6d44a6dc2ec34607c41ec78acf81657248580bf1'

PlugUpdate!
```

I did wonder if I did something weird, but https://github.com/folke/trouble.nvim aligns with the shortcuts that work.

I seem to be on head - https://github.com/folke/trouble.nvim/commit/6efc446226679fda0547c0fd6a7892fd5f5b15d8. Maybe I shouldn't be doing that.

But the latest 3.6 version also does this - see readme in https://github.com/folke/trouble.nvim/tree/40c5317a6e90fe3393f07b0fee580d9e93a216b4 (https://github.com/folke/trouble.nvim/commit/40c5317a6e90fe3393f07b0fee580d9e93a216b4)

**Comment by abhinav** [comment]
Oh, I probably have a pretty old version installed. I haven't run plugin-update in a while.

**Comment by abhinav** [comment]
Upgraded my dependencies.

**Comment by abhinav** [comment]
Thanks

**Pull request merged**
